name: "Create promotion pull request"

on:
  workflow_dispatch:
  push:
    branches:
      - test
      - dev
      - "feature/**"

jobs:
  promote-test-to-main:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/test'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: main

      - name: Reset promotion branch
        run: |
          git fetch origin test:test
          git reset --hard test

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: test
          title: Merging test changes to main
          body: Automatically created pull-request in order to merge changes that were recently pushed to the test branch, back to main
          # assignees: hwinther-tietoevry

  promote-dev-to-test:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
        with:
          ref: test

      - name: Reset promotion branch
        run: |
          git fetch origin dev:dev
          git reset --hard dev

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: dev
          title: Merging dev changes to test
          body: Automatically created pull-request in order to merge changes that were recently pushed to the dev branch, back to test
          # assignees: hwinther-tietoevry

  promote-feature-branch-to-dev:
    runs-on: ubuntu-latest
    if: ${{ contains(github.ref, 'refs/heads/feature/') }}
    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev

      - name: Reset promotion branch
        run: |
          git fetch origin ${{ github.ref }}:${{ github.ref }}
          git reset --hard ${{ github.ref }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}
          branch: ${{ github.ref }}
          title: ${{ github.event.head_commit.message }}
          body-path: .github/PULL_REQUEST_TEMPLATE.md
          assignees: ${{ github.actor }}
          draft: true
