name: "Check PR target branch"

on:
  pull_request:
    types: [opened, reopened, edited]
  pull_request_target:

jobs:
  check_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Check target branch (main)
        if: github.base_ref == 'main' && github.head_ref != 'test'
        run: |
          echo "ERROR: You can only merge to main from test"
          exit 1

      - name: Check target branch (test)
        if: github.base_ref == 'test' && github.head_ref != 'dev'
        run: |
          echo "ERROR: You can only merge to test from dev"
          exit 1
