name: "Add tag on push to main or test"

on:
  push:
    branches:
      - main
      - test

jobs:
  tag-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # used by GitVersion to find the most recent tag outside of this branch

      - name: Debug output
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo context: "$GITHUB_CONTEXT"

          echo "Diff head commit:"
          git diff ${{ github.event.head_commit.id }}
          git diff --stat ${{ github.event.head_commit.id }}
          echo "Lines:"
          git diff ${{ github.event.head_commit.id }} | wc -l

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v40

      - name: List all changed files
        run: |
          for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
            echo "$file was changed"
          done

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        with:
          scheme: semver
          increment: minor
          # TODO: Could we use increment patch when bugfixes land on dev?

      - name: Create tag
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.version.outputs.version }}',
              sha: context.sha
            })
