name: "Add tag on push to main or test"

on:
  push:
    branches:
      - main
      - test

jobs:
  tag-on-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # used by version (git) operations to find the most recent tag outside of this branch

      - name: Check files changed
        id: check-changes
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo context: "$GITHUB_CONTEXT"
          # git diff --name-status ${{ github.event.before }}..${{ github.event.after }}

          diffs=$(git diff --name-status ${{ github.event.before }}..${{ github.event.after }} | wc -l)
          echo "diffs=$diffs"

          if ((diffs > 0)); then
            echo "setting has_diff true"
            echo "has_diff=true" >> "$GITHUB_OUTPUT"
          else
            echo "setting has_diff false"
            echo "has_diff=false" >> "$GITHUB_OUTPUT"
          fi

      - name: Get next version
        uses: reecetech/version-increment@2023.10.1
        id: version
        if: ${{ steps.check-changes.outputs.has_diff == 'true' }}
        with:
          scheme: semver
          increment: minor
          # TODO: Could we use increment patch when bugfixes land on dev?

      - name: Create tag
        uses: actions/github-script@v6
        if: ${{ steps.check-changes.outputs.has_diff == 'true' }}
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'refs/tags/v${{ steps.version.outputs.version }}',
              sha: context.sha
            })
