name: "Update branch"

on:
  push:
    branches:
      - main
      - test

permissions: write-all

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # ref: main
          fetch-depth: 0

      - name: Setup git user
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Update (rebase) test and dev branch
        if: github.ref == 'refs/heads/main'
        run: |
          git checkout test
          git rebase main test
          git push origin test

          git checkout dev
          git rebase test dev
          git push origin dev

      - name: Update (rebase) dev branch
        if: github.ref == 'refs/heads/test'
        run: |
          git checkout dev
          git rebase test dev
          git push origin dev
